# Generated by Django 5.0.7 on 2024-10-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classinfo',
            fields=[
                ('classcode', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('classhour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('studentname', models.TextField(max_length=100)),
                ('studentno', models.CharField(max_length=15)),
                ('parentno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectcode', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('subjectname', models.TextField(max_length=100)),
                ('totalhour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutorid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tutorname', models.TextField(max_length=100)),
                ('tutorno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('status', models.TextField(max_length=100)),
                ('classcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoring4Pointer.classinfo')),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoring4Pointer.student')),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='subjectcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoring4Pointer.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tutorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoring4Pointer.tutor'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='tutorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoring4Pointer.tutor'),
        ),
    ]
