# Generated by Django 5.0.7 on 2024-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoring4Pointer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentpassword',
            field=models.CharField(default='afiq123', max_length=8),
        ),
    ]
