# Generated by Django 5.0.7 on 2024-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoring4Pointer', '0002_student_studentpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutorpassword',
            field=models.CharField(default='afiq123', max_length=8),
        ),
    ]
