# Generated by Django 5.0.7 on 2024-10-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoring4Pointer', '0003_tutor_tutorpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutoring4Pointer.tutor'),
        ),
    ]
